assets/client_installer/reportcommon
This fix will allow MunkiReport-PHP when running on either OS X 10.10
Server or a newer version of Apache to use TLSv1 as the default
protocol when submitting data as Python by default uses SSL. Thanks to
https://gist.github.com/flandr/74be22d1c3d7c1dfefdd for the fix.
=> Add TLSv1 support for URLLIB2

app/views/client/power_tab.php
While testing the recently added power module (which is awesome, by the way!), I noticed that the temperature was just being pulled as a raw int from the database onto that page, leading to ugly temperature display. I poached the conversions from elsewhere and included logic to not display the temperature at all if no value is present.
Only question / todo - would it be preferable to put the temperature label in the left column to match the ones above it (e.g. mAh), or is the right column ok?
=> Add temperature_unit processing to the client tab

config_default.php
This prevents displaying an Uncaught Exception when nothing has been
specified to be tracked.
=> Added Safari as the default app to track

app/views/client/munki_tab.php
The managed installs list table on the managed software tab is now
sortable using dataTables. Enhancement Request #178. Thanks for bearing with me on the pull requests and sorry I am such a gitiot.
=> Make managed installs list sortable

assets/locales/en.json
I didn't find the battery widget labels to be very intuitive - here are my suggestions for new ones. If those don't work, maybe a tooltip with the full text and a short explanation of what each status might mean?
(updated with correct file for localization!)
=> Update widget labels

app/views/widgets/bound_to_ds_widget.php, app/views/widgets/client_widget.php, app/views/widgets/disk_report_widget.php, app/views/widgets/uptime_widget.php
I adjusted some widgets order of output so the dashboard would have a more consistent look to it.  In the default output of some widgets is error->success left to right so the buttons were red/orange/green.  Others output success->error so they were green/orange/red.  My edits make it consistent error->success so buttons are red->green and make a more unified look.  Below are screencaps of the default vs. edited output.
=> Wip - edited output of widgets to be more consistent

app/modules/directory_service/scripts/directoryservice.sh
The original directoryservice.sh script assumed the hostname was the AD binding object name for the computer object.  That's not always the case.
I've added code to detect the binding name from the AD config on the machine and use that to look up computer object comments with dscl.
We do not have comments in our computer objects so anyone that can test this change would be appreciated.
=> Adjust ActiveDirectory computer name detection

app/modules/ard/scripts/install.sh, app/modules/bluetooth/scripts/install.sh, app/modules/certificate/scripts/install.sh, app/modules/crashplan/scripts/install.sh, app/modules/directory_service/scripts/install.sh, app/modules/disk_report/scripts/install.sh, app/modules/displays_info/scripts/install.sh, app/modules/filevault_status/scripts/install.sh, app/modules/inventory/scripts/install.sh, app/modules/localadmin/scripts/install.sh, app/modules/network/scripts/install.sh, app/modules/power/scripts/install.sh, app/modules/printer/scripts/install.sh, app/modules/profile/scripts/install.sh, app/modules/servermetrics/scripts/install.sh, app/modules/service/scripts/install.sh, app/modules/timemachine/scripts/install.sh, app/modules/warranty/scripts/install.sh, app/views/install/install_script.php, assets/client_installer/reportcommon
An updated version of Pull Request #192:
Submit Munki's additional HTTP headers along with any curl/purl connection, if the 'UseMunkiAdditionalHttpHeaders' MunkiReport pref is set on the client (this is helpful if you're hosting Munki & MunkiReport on the same server while also using [HTTP Basic Auth](https://github.com/munki/munki/wiki/Using-Basic-Authentication)). Also modernizes/improves curl command building in install_script.php & modules' install.sh scripts to correctly handle complex quoted arguments (like HTTP headers).
If installing from a server that requires HTTP Basic auth, you may want to run the installer as follows:
sudo defaults write /Library/Preferences/MunkiReport UseMunkiAdditionalHttpHeaders -bool YES
sudo /bin/bash -c "$(curl -s -H "Authorization: Basic …
=> Additional HTTP Headers/Basic Auth Support for install & submit

app/modules/location/README.md, app/modules/location/location_controller.php, app/modules/location/location_model.php, app/modules/location/scripts/install.sh, app/modules/location/scripts/location.py, app/modules/location/scripts/uninstall.sh, app/views/client/client_detail.php, app/views/client/location_tab.php, assets/locales/en.json
This is a complete rewrite of #189 using CoreLocation to locate your Mac. However, we're still using Google's geocoding api for reverse address lookup.
Lots of community members helped make this possible:
@bochoven, @gmarnin, @pudquick, & @arubdesu all directly have code snippets that were used in creating this pull request. So :+1: to them.
This module is limited to 10.8 - 10.11. I wanted to support 10.6/10.7 however they use sqlite databases for Location Services so you'll need to upgrade those systems if you wish to use this module.
On each munki preflight run Location Services will be enabled, and the system Python binary will be given access to Location Services. ~~Due to how Location Services and the locationd daemon interact the first run to enable all the services takes about 50 …
=> CoreLocation Module Squashed Commit

app/modules/location/README.md, app/modules/location/scripts/location.py, app/views/client/location_tab.php, app/views/listing/location.php, assets/locales/de.json, assets/locales/en.json, assets/locales/fr.json, assets/locales/nl.json, assets/locales/ru.json
Pretty big update to handle more edge cases within the location module. The advanced logging should provide better feedback to admins when things don't go as planned. 
Improvements
* This should write output to `./cache/location.plist` on every run
* Check if we have a wireless adapter before enabling and running
* We write to the plist using a method now...much cleaner 
* Add a location listing
* Enabled logging within the `location.py` script
* Verbose output using `-v` and `-vv`
* Rename ReportPrefs key from  `google_api_lookup` to `location_address_lookup`. These preferences should include the module name in the key to make it more clear.
* Update module Readme to match updates 
This script does **not** enable the wireless adapter if it turned off. Instead we make the `currentstatus` …
=> Location updates

app/modules/printer/scripts/printer.py
As promised the Printer script fixed. No longer shall the preflight script exit 1.
I got a little lazy and only tested in 10.6, 10.7, 10.9 and 10.11. Even if 10.8 and 10.10 are different the exception for KeyError should cover us.
The 'shared' key is better as it is present on 10.6-10.11 while the 'printersharing' key was only on later OS releases.
Also linted the script while it was open.
=> Fix printer.py to handle when sharing is off

app/modules/security/scripts/security.sh
If less than 10.7 we should output data for Gatekeeper.
If less than 10.11 we should output data for SIP.
=> security module - output data on older devices

app/views/install/install_script.php
Mainly, this fixes so that submit.preflight is not mysteriously missing from the generated PKG when downloading from a munkireport-php server with an insecure certificate. All other curl-calls preserve --insecure, and therefore work.
=> preserve curl options when curl-ing submit.preflight

app/modules/security/scripts/security.sh
he output from csrutil status has a period at the end of enabled/disabled
=> Fix incorrect status on SIP

app/modules/wifi/scripts/install.sh
the wifi install script does not use the set of options defined, so fails on e.g. self-signed certificates
(Supersedes #453 )
=> use proper curl command to preserve options

app/modules/inventory/scripts/install.sh, app/modules/inventory/scripts/inventory_add_plugins, app/modules/munkireport/scripts/install.sh
Currently munkireport is hard coded to munki's default install directory settings. If you change the ManagedInstallDir Preference in munki it breaks munkireport. The proposed changes uses CoreFoundation's CFPreferences to check how munki is configured (if at all) and configure munkireport accordingly.
=> Dynamic Munki Support

app/views/auth/login.php
Sometimes HTTPS is set to "off"
Basically assuming its not secure if it is not equal to "on"
=> Fix for SSL detection

assets/locales/en.json
The hover title for the Events widget on the dashboard was incorrect due to recent changes to only show the last 50 events.  The previous title stated the events listed were from the last hour.
=> Events hover title to "Recently generated events"

app/modules/power/power_model.php
Addressed divide by 0 errors when no battery is present.
BR https://github.com/munkireport/munkireport-php/issues/542
=> Adjusted for div by 0 error.

app/modules/disk_report/scripts/disk_info
Skips volumes which are not mounted, to prevent reporting wrong free space as zero bytes.
=> disk_report: Skip non-mounted volumes

config_default.php
As discussed in Slack, if a trailing slash is used in this conf, the DS module throws an exception, so updating the sample config.php file. Thanks!
=> Update deploystudio_server sample conf to omit trailing slash

app/modules/usb/scripts/usb.py
This wasn't catching a USB attached Drobo as mass storage and had it filed it under "unknown".
Added `removable_media` to catch the mass storage device.  
XML Output from an attached Drobo on a system running 10.11.6 is:
```
<dict>
<key>_name</key>
<string>Drobo</string>
<key>bcd_device</key>
<string>0.00</string>
<key>bsd_name</key>
<string>disk2</string>
<key>bus_power</key>
<string>1000</string>
<key>bus_power_used</key>
<string>0</string>
<key>detachable_drive</key>
<string>yes</string>
<key>device_speed</key>
<string>high_speed</string>
<key>extra_current_used</key>
<string>0</string>
<key>location_id</key>
<string>0xfa130000 / 3</string>
<key>manufacturer</key>
<string>Drobo</string>
<key>partition_map_type</key>
<string>guid_partition_map_type</string>
<key>product_id</key> …
```
=> USB module edit

app/modules/managedinstalls/scripts/managedinstalls.py, app/modules/munkireport/scripts/munkireport.py
making the postflight munkireport and managedinstalls scripts more dynamic for supporting the move of managed_install_dir as well as some pep8 cleanup.
=> Dynamic postflight scripts.

app/modules/gpu/gpu_model.php
GMA 950's use a hardcoded string for memory, changed to display memory value.
=> Fix Intel GMA GPUs

app/modules/machine/views/hardware_listing.php
Hardware listing was missing the report title.
=> Hardware localization fix for Listing title

app/modules/disk_report/locales/de.json, app/modules/disk_report/locales/en.json, app/modules/disk_report/locales/fr.json, app/modules/disk_report/views/disk_listing.php
Storage Report was missing a localization.
Added. I don't have the translations for German or French so I just added it in English.
=> Fixed localization for media type in disk_listing (Storage Report)

app/modules/appusage/scripts/install.sh, app/modules/caching/scripts/install.sh, app/modules/certificate/scripts/install.sh, app/modules/security/scripts/install.sh, app/views/install/install_script.php
Build runs were showing errors on the local paths:
```
bash -c "$(curl http://example.com/munkireport/index.php?/install)" bash -i ~/Desktop
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 33382    0 33382    0     0  3298k      0 --:--:-- --:--:-- --:--:-- 3622k
Preparing /var/folders/cn/92l5b1dn49z2zk_xt43n84kh0000gg/T/mrpkg.v1uu5Kqo/install_root/usr/local/munki/ and $3/Library/Preferences/MunkiReport
BaseURL is http://example/munkireport/
Retrieving munkireport scripts
Configuring munkireport
+ Installing appusage
touch: /usr/local/munki/preflight.d/cache/appusage.csv: Permission denied
+ Installing ard
+ Installing security
override rw-r--r--  root/wheel for /usr/local/munki/preflight.d/cache/security.txt? …
```
=> Adjusted cache paths in module install scripts

app/modules/smart_stats/migrations/002_smart_stats_remove_fake_null.php, app/modules/smart_stats/smart_stats_model.php
Added a 2nd migration to update the `error_count` table and replace value with NULL where appropriate. This table was missed in the 001 migration.
=> Smart stat error count table fixup

app/modules/smart_stats/views/smart_stats_listing.php
The smart errors are most interesting at a glance, especially when highlighted red.  Even on my wide screen 27" monitor it was off to the right and required scrolling to see.
This PR moves the columns to the left so they are visible on page load w/o needing to scroll.
=> Moved SMART errors left in listing to be visible w/o scrolling.

config_default.php
Adds a semicolon so users can copy/paste without php error.
Replaces PR: #753
=> docs: Update default_config.php

app/modules/directory_service/views/directory_tab.php
Per https://macadmins.slack.com/archives/C066NK3K5/p1492767504225894
```
As you can see, the last else-clause results in `$('#directoryservice-createmobileaccount').text("");` rather than `$('#directoryservice-requireconfirmation').text("");`
```
Fixed the else clause to match the content of prior if/else checks.
=> Updated else clause output reference

app/modules/munkireport/scripts/munkireport.py
Current Error reporting for the munkireport module has duplicate entries since Munki reports an error for a missing catalog during different phases of the munki run.
This PR pares the list of Errors and Warnings down to just unique entries.
On my machine I have many different testing and development catalogs for titles that aren't always in testing or production. I want the software when they are imported into munki and in those catalogs, so I leave the catalogs in the manifest.  In MR I see 40 munki errors (10 errors, 4x).  When eyeballing the Events log, having a more accurate representation of the number of errors clients are seeing would help flag actual issues.
-Eric
=> Report only unique errors and warnings.

app/modules/security/views/security_listing.php
@poundbangbash pointed out on Slack that clients who hadn't checked in yet showed as disabled in the listing - this fix leaves that column blank when the DB value is null.
=> update so clients who have not checked in don't show as disabled

app/modules/certificate/certificate_model.php, app/modules/certificate/locales/de.json, app/modules/certificate/locales/en.json, app/modules/certificate/locales/fr.json
By default Lets Encrypt certs expire in 3 months.  With a 3 month "soon" all LE certs would perpetually be shown as expiring soon and in turn cause awareness fatigue toward the expiring soon warning.
Setting the notification of a cert expiring to 1 month would allow for time to address the expiring cert but also give notice to the admin regarding the upcoming expiration.
=> Adjust 'soon' to be one month instead of 3

app/modules/certificate/scripts/cert_check
LetsEncrypt saves its certs in /etc/letsencrypt/live/<domain> by default.
This adds the check for certs there.
=> Add LetsEncrypt specific path check

app/modules/certificate/views/certificate_listing.php
The listing still had the warning badge set for < 90 days.
Changed to < 30 days to match the widget "soon" timing.
=> Update listing view to higlight < 30 days as warning

app/modules/certificate/scripts/cert_check
Reworked the directory check test to suppress errors in the MR run output.
=> Fix run errors when directories don't exist.

app/modules/reportdata/views/uptime_widget.php
If the timeframes for the uptime widget didn't' have any matches the value returned from the sql query was "null" and the widget displayed no value instead a definitive 0.
This checks the values of the returned data to see if it is null, if so, explicitly sets it to 0.
I'm not sure if this is the correct place to fix this so feel free to adjust as necessary.  I didn't see an easy way to return this value in the model since the values are coming straight from the sql query.
=> Set widget timeframe variable to 0 if sql search in model returns null

app/modules/certificate/certificate_model.php, app/modules/certificate/migrations/002_certificate_bigint_cert_exp_time.php
Errors in the certificate module from int values larger than the signed int allowed values.
This PR adds a migration to change cert_exp_time from INT to BIGINT to allow for larger values.
Tested by checking out `master`, dropping the `certificate` table, loading the listing in a browser to create the table with `cert_exp_time` set to INT and schema version 1.
Checked out this branch, reloaded the listing in the browser.  The migration succeeded per the webpage. Confirmed by observing the type for `cert_exp_time` is now BIGINT.
=> Adjust cert_exp_time to be BIGINT due to values exceeding support of INT

app/views/admin/business_units.php
on the `admin/show/business_units` page, machine groups for each business unit are ordered by their id. This makes it difficult when you have a bunch of machine groups under a business unit and are trying to verify that everything is there that needs to be. This takes the machine groups and orders them by name before going on to render them.
=> Update BU to sort MGs by name

app/views/admin/business_units.php
Finishes up #807. Machine Groups were sorted in the Business Unit listing, but when you clicked edit they were unordered in the edit modal. Oops!
=> Add MG sorting in edit modal

app/modules/smart_stats/views/smart_stats_tab.php
The module model changed to use 0 instead of nulls where no data was present which caused the client tab to highlight the error fields red even if the count was 0.
This checks to make sure the value is not 0 before it highlights the cell red.
=> Tab only highlights warning if errors > 0

app/views/install/install_script.php
Otherwise it is never updated with the BASEURL that is set with getopts
=> Moving TPL_BASE assignment after options are read

app/modules/munkiinfo/views/munkiinfo_munkiprotocol_widget.php
Two changes:
1) Adjusted the search criteria when buttons are pressed in the widget.  Previously it was trying to search for 'munkiprotocol' and 'https' for example but that would result in 0 hits since that data is across two columns.  I adjusted the search to just look for 'munkiprotocol'
2) Re-worked the buttons to be grayed out if no data is present for that criteria.
=> Munki protocol widget fix

assets/images/favicons/safari-pinned-tab.svg
Per Discussion on munkireport slack channel:
Here is a new pinned tab SVG icon that fixes the issues of the original "Tombstone" icon.
=> Updated SVG icon for Safari Pinned Tab. Resolved "Tombstone" Icon

app/controllers/unit.php
Having more than a few machine groups leads to an confusing filter view because the list was sorted by id and not by name. This pull request now sorts this list by group name.
=> Sort machine groups by name

app/modules/munki_conditions/README.md, app/modules/munki_conditions/locales/en.json, app/modules/munki_conditions/munki_conditions_controller.php, app/modules/munki_conditions/munki_conditions_model.php, app/modules/munki_conditions/provides.php, app/modules/munki_conditions/scripts/install.sh, app/modules/munki_conditions/scripts/munki_conditions.py, app/modules/munki_conditions/scripts/uninstall.sh, app/modules/munki_conditions/views/client_munki_conditions_tab.php, app/modules/munki_conditions/views/munki_conditions_listing.php
resolve #627 from @flammable.
resolve #835 from @flammable.
Please let me know if you have any suggestions.
For one, I didn't know how to get the location of ManagedInstallReport.plist from prefs so it is hardcoded in the client script.
Second, all values are truncated and stored as 255 character strings. Would it be preferred to utilize BLOB so that JSON could be used to store arrays?
Munki Conditions Module
=======================
Provides the results of [munki conditions](https://github.com/munki/munki/wiki/Conditional-Items), allowing admins to easily generate their own reportable datapoints without creating custom MunkiReport modules. Condition scripts are even easier to create using [munki-facts](https://github.com/munki/munki-facts).
Admin-Provided Condition scripts are found in …
=> Module for admin-provided munki conditions

app/modules/gpu/gpu_model.php
10.13 changed the output of some GPU vendors, this adjusts for the change and fixes a problem with legacy ATI GPUs not having the correct name
=> Fix GPU vendors for 10.13

app/modules/usage_stats/scripts/install.sh
Installation failed for the module due to the install script referencing "usage_stats.sh" when the file is "usage_stats" in the scripts directory.
=> Fixed source filename reference

app/modules/softwareupdate/migrations/2017_12_19_200401_softwareupdate.php
Column "automaticcheckenabled" can be -1, changed datatype to be int
=> Fix datatype in softwareupdate v3 migration

public/assets/client_installer/report_broken_client
CFPreferences handles prefs set by a configuration profile. Currently uses `osascript -l JavaScript`, so it's 10.10+ only.
=> Use CFPreferences to read BaseUrl and Passphrase.

app/modules/detectx/README.md, app/modules/detectx/detectx_controller.php, app/modules/detectx/detectx_model.php, app/modules/detectx/locales/en.json, app/modules/detectx/locales/fr.json, app/modules/detectx/provides.php, app/modules/detectx/scripts/install.sh, app/modules/detectx/scripts/uninstall.sh, app/modules/detectx/views/detectx_listing.php, app/modules/detectx/views/detectx_tab.php, app/modules/detectx/views/detectx_widget.php
Will pull a json file from DetectX granted the admin deploying this module places it in the cache dir.
=> DetectX Module

app/views/install/install_script.php
Bad quoting of $3 in the installer postflight caused 0600 permissions on the MunkiReport.plist preference file.
=> Fix installer postflight

app/controllers/clients.php, app/modules/security/locales/en.json, app/modules/security/migrations/2018_01_19_234938_security.php, app/modules/security/scripts/security.py, app/modules/security/security_model.php, app/modules/security/views/security_listing.php, app/views/client/summary_tab.php
The current SSH information in the Client Details and Security Listing doesn't include group or directory based users.
The changes I incorporated gather user and group information from the com.apple.ssh_access group.
Users that are explicitly added in the Remote Login Preference pane are listed in the GroupMemberships key.  
Groups are a little trickier as they are only stored as UUIDs.  Using a couple loops those UUIDs can be converted to group names.  
Since groups are now supported I thought it didn't make much sense to use the previous method of evaluating each local user against the com.apple.ssh_access list to check if they are members.  That method won't catch directory based groups would not list all of it's members as SSH Users.
Since this is my first go at a v3 migration I'd …
=> Security ssh detection update

app/modules/smart_stats/views/smart_overall_health_test_widget.php
The report/widget title was missing due to misconfigured localization. Fixed it.
=> Smart stats report title fix

app/modules/machine/machine_controller.php, app/modules/machine/provides.php, app/modules/machine/views/osbuild_widget.php, app/modules/reportdata/views/clients.php, public/assets/locales/en.json
Create an os build widget (unabashedly based on the existing os build widget) and add it to the Clients Report by default. I served this using the included Dockerfile and client [os builds were available](https://i.imgur.com/BzZpCQ5.png) on the widget as I'd expect.
Any feedback appreciated!
=> Create widget for os build breakdown and add it to the client report

app/modules/tag/locales/en.json
To make the listing's titles uniform
=> Make tag report name title case

public/assets/css/system/database.css
The background color on the database log view is hard coded and makes it hard to read the content on some themes due to font/background contrast.  Removing the background color defaults back to the theme's CSS. I didn't see any issues in cycling thru the different themes.
=> Adjust database log view to use theme for readability.

config_default.php, public/assets/js/clients/client_detail.js
Using the method to get the current username from https://github.com/munkireport/munkireport-php/issues/877 this change allows an admin to use a custom ssh_link config to replace the username with the current user logged into Munkireport.  This is beneficial when directory based logins are used.
Adding `$conf['ssh_link'] = "ssh://%u@%s";` to config.php will result in the username being substituted in.  If the custom config is not in config.php the %u substitution does not take place.
-Eric
=> Add option to use current username for ssh link

app/modules/security/migrations/2017_02_09_234938_security.php
The migration doesn't allow null values and failed migration if values are blank.
=> Fix security module migration

app/modules/extensions/scripts/extensions.py
The variables aren't declared and are only set inside an `if` condition.  If the condition is false the variables never get set and errors out.
=> Added variable declaration

app/controllers/clients.php, config_default.php, public/assets/js/clients/client_detail.js
Attempt to address issue #878
This gives the admin the option to use the internally detected network IPs from the network table for the SSH and VNC remote control links.
If a machine has multiple internal IP addresses only one is returned.  As long as it has one internal IP on wired or wireless it should be reachable. 
-Eric
=> Added local network ip option for vnc and ssh links

app/lib/munkireport/AuthSaml.php
Allowing for a `disable_sso_sls_verify` configuration option.  This was brought about when trying to integrate with Okta for single logout.  Okta insists on sending a HTTP_POST when confirming an SLO request which the underlying Onelogin Saml-PHP framework is not currently compatible with. The Sign out process doe in fact complete but our app is not able to verify the HTTP_POST response.
I am proposing that by setting this `disable_sso_sls_verify` to true, if we encounter an error on SLO processing, we assume the request succeeded, kill the current user session and redirect to a logout page.
I can update the wiki if accepted.
=> Add disable_sso_sls_verify config option

app/controllers/clients.php, app/modules/localadmin/scripts/localadmin, app/modules/reportdata/migrations/2018_04_12_064804_reportdata_add_uid.php, app/modules/reportdata/reportdata_model.php, app/modules/reportdata/reportdata_processor.php, app/modules/user_sessions/locales/en.json, app/modules/user_sessions/locales/fr.json, app/modules/user_sessions/migrations/2018_04_12_055955_user_sessions_add_user_uid.php, app/modules/user_sessions/scripts/user_sessions.py, app/modules/user_sessions/user_sessions_model.php, app/modules/user_sessions/views/user_sessions_listing.php, app/modules/user_sessions/views/user_sessions_tab.php, app/views/client/summary_tab.php, public/assets/client_installer/reportcommon, public/assets/client_installer/submit.preflight
Attempt at https://github.com/munkireport/munkireport-php/issues/1057
This PR gathers the UID of users processed in reportdata and user_sessions.
The user_sessions listing, tab, local admin listing, and client summary page have been adjusted to display the UID information.
The added column requires a database migration for reportdata and user_sessions modules.
User sessions client tab:
Client summary:
Local Admin listing:
User Sessions listing:
-Eric
=> Add UID to reportdata, user_sessions module, localadmin module, and client summary

app/modules/security/scripts/security.py
This edit checks the com.apple.local.ard_interact group for GroupMemberships for allowed ARD users. This method is used for adding access for network based users.
=> Add check network based users added to com.apple.local.ard_interact

app/controllers/database.php, app/views/system/database.php
The JSON response would be quite different in the PDOException caught vs migration failed error cases which meant that PDOExceptions displayed no information about the error.
This hotfix means that errors are always shown when applying migrations.
=> Fix an issue where failed migrations would not display an error

app/controllers/system.php, app/lib/munkireport/Database.php, app/views/system/status.php, public/assets/locales/en.json
=> Implement db size calcs

app/views/admin/business_units.php
$.each was converted back to old-style for loop because the return; did not shortcut the execution of $.each and caused it to iterate over empty array indices.
=> FIX #1074: Loop iterated over empty array indices in machine group delete

app/modules/extensions/migrations/2018_02_12_164431_extensions_add_teamid.php
Changed to use make new table, copy data, drop old table method of renaming a column for SQLite compatibility. Should fix issue #1038
=> Changed Extensions add teamid column method

app/modules/sentinelonequarantine/README.md, app/modules/sentinelonequarantine/locales/en.json, app/modules/sentinelonequarantine/migrations/2018_05_03_152424_sentinelone_add_quarantine_files.php, app/modules/sentinelonequarantine/provides.php, app/modules/sentinelonequarantine/scripts/install.sh, app/modules/sentinelonequarantine/scripts/sentinelone_quarantine.py, app/modules/sentinelonequarantine/scripts/uninstall.sh, app/modules/sentinelonequarantine/sentinelonequarantine_controller.php, app/modules/sentinelonequarantine/sentinelonequarantine_model.php, app/modules/sentinelonequarantine/views/sentinelone_quarantine_client_tab.php, app/modules/sentinelonequarantine/views/sentinelone_quarantine_listing.php
This module can be standalone but only shows the files that are quarantined by SentinelOne. It doesn't include the status of the SentinelOne agent. The `sentinelone` module handles that.
This module only gathers the paths and UUIDs of quarantined files for reference.
Files can be released from quarantine on the client machine by UUID and path, hence having this information handy.
The module includes a Listing:
And a client tab view:
The Tab view includes a badge count to easily see if there are quarantined files from the tab listing:
=> SentinelOne Quarantine module to compliment the SentinelOne module.

app/controllers/database.php, app/views/system/database.php
To fix migration issues, there is no migration pretend mode for now, and no estimate on number of migrations to perform. This is temporary in order to make migrations functional.
Additionally, more errors are displayed in the migration log.
=> No migration pretend mode

app/config/app.php
Not sure if all agree, but I think having the (?) symbol be visible by default makes sense.
=> Make showing help link default to true

app/config/auth/saml.php
Add support for additional onelogin/php-saml parameters (specifically 'x509cert' and 'privateKey' to SP and 'binding' to IDP SSO and SLO).
=> Add support for additional onelogin/php-saml parameters

README.md
When I was looking through the code I was a bit confused because I couldn't find the modules anymore. The old module creation page says the method is deprecated and needs to be updated but doesn't link to the new [module overview](https://github.com/munkireport/munkireport-php/wiki/Module-Overview) page that describes the changes.
I added a small note about modules in the contributing section of the README.md. This should help guide people that are interested in contributing to the modules.
I was also thinking of adding a note and link to the top of these wiki pages, but I didn't want to change without approval.
- [How to create a module](https://github.com/munkireport/munkireport-php/wiki/How-to-create-a-module)
- [How to create a module - …
=> Add note about modules to contributing section

app/views/install/install_script.php
only materialized itself when additional headers where set: in this case
they where not passed quoted correctly
=> fix one forgotten case of curl quoting in install script

.env.example
The default .env.example will not work because of the CONNECTION_DATABASE string. Commenting it out by default and entering more clarifying text to guide the user.
=> Commenting CONNECTION_DATABASE out in .env.example

app/views/install/install_script.php
This change normalizes the BaseURL provided and adds a trailing slash if one is not present.
Another slash correction is made in the `TPL_BASE` value so there are no double slashes in the URL. Some web servers (like Caddy) do not handle double slashes and fail to download resources.
I've tested this on my apache setup and it works both with and without my changes.
=> Fix issue with extra slashes in install script URL

app/views/client/summary_tab.php
Was getting the following error on this branch when trying to view a client detail summary page:
```Parse error: syntax error, unexpected 'endforeach' (T_ENDFOREACH), expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in /Volumes/ExtHD/munkireport-php/app/views/client/summary_tab.php on line 14```
Changing line 10 to be `<?php endif ?>` instead of `<?endif?>` loads the summary data and customized modules in the web view.
=> Fix php endif

.pre-commit-config.yaml, build/mr_upgrade.py, build/release/make_munkireport_release.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/FoundationPlist.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/constants.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/display.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/munkilog.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/phpserialize.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/prefs.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/purl.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/reportcommon.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/reports.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/utils.py
(Replaces #1253.)
This change would implement a [Pre-Commit](https://pre-commit.com) configuration that prevents contributors from committing unless certain basic tests pass. As configured here, the tests include:
- [Black](https://black.readthedocs.io/en/stable/) formatting for Python files
- All PHP files pass `php -l` linting check
- No added files exceed 100KB
- No leftover merge conflicts within files
- UNIX style line endings only
Additional hooks have been included in the config file but remain commented out, because they will require a bit more work to initially implement. These future tests could include:
- Eliminating unnecessary trailing whitespace
- Standardizing file endings
- YAML syntax checking (which would catch issues like the one fixed in #1252)
- Verifying executable …
=> Add pre-commit hooks for PHP linting, Python Black, and other basics (conflict resolved)

public/assets/js/googlemaps/markerclusterer.js
Reverts munkireport/munkireport-php#1321
This should not be changed in the master branch and why is this in core?
=> Revert "Update markerclusterer.js"

app/views/system/status.php
SOAP extension was used only by defunct GSX API
=> Remove SOAP Check

public/assets/client_installer/payload/usr/local/munkireport/munkilib/reportcommon.py
Big Sur reports its OS version as 10.16 or 11.x depending on which SDK the calling mechanism is compiled against.  There is an environment variable "SYSTEM_VERSION_COMPAT" that can be used to make the output more predictable.
The built in Python shipped with BigSur hard codes the variable so all Big Sur installs are reporting as 10.16.0.
Furthermore, 10.16.0 is a frozen version of the OS regardless of updates.  Any machine reporting as 10.16.0 will always only report as 10.16.0 even if the real OS version is 11.2.3, etc.  
This PR is to consider changing how the OS is detected to shell out and use the environment variable to report the actual OS version instead of the compatibility-mode version.
This was tested against 10.12-11.0.1 systems. All are reporting properly without error.
-Eric
=> Use env variable "SYSTEM_VERSION_COMPAT" and shell for OS detection

composer.json
Similar to Sphens PR, just to get tests passing again
=> Update PHPass dependency to new maintainer until we know impact.

public/assets/client_installer/payload/usr/local/munkireport/munkilib/purl.py, public/assets/client_installer/payload/usr/local/munkireport/munkilib/reportcommon.py, public/assets/client_installer/payload/usr/local/munkireport/munkireport-runner
Update purl.py to store response as "data" aka bytes not str(), which solves an issue when purl tries to convert every chunk in the response to str() and ends up double encoding the response data.
Update reportcommon.py to decode the bytes returned by Purl
Minor PEP code style changes.
=> python3 compatibility in purl/reportcommon

build/templates/module/py-install.stub, build/templates/module/py-module_script.stub, build/templates/module/py-processor.stub, build/templates/module/py-uninstall.stub
I'd like to add an option for `please make:module` to use python vs bash, so consider this a feature request as well 😅 . I gathered how to do the `.stub` files, but have not dug into the actual template. Not sure if it's possible to give the user the choice, but I think that would be ideal.
=> Adding python/json installer/file types for module template

.gitignore, MR/Kiss/Core/View.php, app/Http/Controllers/Api/SearchController.php, app/Machine.php, app/ReportData.php, config/_munkireport.php, config/app.php, config/scout.php, routes/api.php, webpack.mix.js
Add SearchController for submitting searches for each model type.
Make Machine and ReportData searchable
Put search feature behind a feature flag `ALPHA_FEATURE_SEARCH`.
Add Laravel Scout and the TNT Search Provider as a lazy option
Add Laravel Scout Default Config
Add search routes
Ignore TNTSearch index in .gitignore
=> Global search merge from scout branch (alpha)

app/Http/Controllers/AdminController.php, app/Http/Controllers/Client/ReportController.php, app/Http/Controllers/InstallController.php, app/Http/Controllers/LocaleController.php, app/Http/Controllers/ManagerController.php, app/Http/Controllers/ModuleController.php, app/Http/Controllers/ModuleMarketplaceController.php, app/helpers/bootstrap_helper.php, app/helpers/config_helper.php, app/helpers/env_helper.php, app/helpers/model_lookup_helper.php, app/helpers/site_helper.php, app/lib/munkireport/BusinessUnit.php, build/config_to_env, config/logging.php, docs/illuminate/v6-upgrade-guide.md, resources/views/admin/business_units.php, resources/views/auth/login-old.blade.php, resources/views/error/client_error.php, resources/views/errors/426.blade.php, resources/views/layouts/app.blade.php, resources/views/layouts/mr.blade.php, resources/views/layouts/spa.blade.php, resources/views/partials/head.php, routes/admin.php, tests/Unit/helpers/ModelLookupHelperTest.php
Add deprecation logging to deprecated API's with opt-in log file
Lots of docblocks explaining deprecated API's and replacements
Attempt to remove deprecated API usage from core.
Go back to legacy implementation of Business Units as the new one is not ready.
Remove several functions from v5 helpers library.
=> Remove more legacy code

public/assets/client_installer/payload/usr/local/munkireport/munkilib/reportcommon.py
=> Fix running system_profiler on Apple Silicon Macs

app/config/auth/env.php, app/helpers/config_helper.php, app/lib/munkireport/AuthEnv.php, app/lib/munkireport/AuthHandler.php, app/views/partials/head.php
Adds auth mechanism `ENV` that is based on an environment variable set by a server
This allows MunkiReport's auth to be configured in alignment with standard auth mechanisms available in some HTTP servers, like e.g. Apache HTTPd.  With auth set to `ENV`, MunkiReport knows that it has to look for a value of an environment variable to determine the name of the user logged in.  The name of the environment variable is configurable, set to `REMOTE_USER` by default.
=> add auth based on server env var
