app/modules/power/README.md
app/modules/power/power_controller.php
app/modules/power/power_model.php
app/modules/power/scripts/install.sh
app/modules/power/scripts/power.sh
app/modules/power/scripts/uninstall.sh
app/views/client/client_detail.php
app/views/client/power_tab.php
app/views/listing/power.php
app/views/report/power.php
app/views/widgets/power_battery_condition_widget.php
app/views/widgets/power_battery_health_widget.php
assets/locales/de.json
assets/locales/en.json
assets/locales/nl.json
config_default.php

I rebuilt kene101’s power module - this time on the latest branch. I am
currently using it on my server with no issues.

kene101 Power Module - NEW

---

app/controllers/auth.php

was kind of difficult to keep track of things

indent auth controller

---

assets/locales/dataTables/ru.json

Added Russian translation for dataTables JSON file.

Russian localization

---

app/modules/profile/README.md
app/modules/profile/profile_controller.php
app/modules/profile/profile_model.php
app/modules/profile/scripts/install.sh
app/modules/profile/scripts/profile.py
app/modules/profile/scripts/uninstall.sh
app/views/client/client_detail.php
app/views/client/profile_tab.php
app/views/listing/profile.php
app/views/profile/profileitem_detail.php
assets/css/style.css

Created a module for reporting computer profile information. Let me know what you think.

Profile Reporting Module

---

config_default.php

Define each widget's size and how it works in the responsive design.

Detailed Dashboard widget layout

---

app/migrations/bluetooth_model/001_bluetooth_model_columns_to_integers.php
app/modules/bluetooth/bluetooth_model.php
app/modules/bluetooth/scripts/bluetooth.sh
app/views/client/bluetooth_tab.php
app/views/listing/bluetooth.php
app/views/widgets/bluetooth_battery_widget.php
config_default.php

this is a follow up of #143.
Some things are old and need tuning

Bt model migration

---

app/views/widgets/hardware_age_widget.php
assets/js/munkireport.js

Allow for graphs to have reversed colors

---

app/controllers/clients.php
app/modules/security/README.md
app/modules/security/scripts/install.sh
app/modules/security/scripts/security.sh
app/modules/security/scripts/uninstall.sh
app/modules/security/security_controller.php
app/modules/security/security_model.php
app/views/client/summary_tab.php
app/views/listing/security.php
assets/locales/en.json

First pass at a security module for issue #371 
Currently this module supports Gatekeeper status and SIP status. Status is reported on the Dashboard and on the Security listing page.

Security Module

---

config_default.php

Added wifi_state and printer to the dashboard layout section

dashboard widget documentation additions

---

app/modules/location/location_model.php
app/modules/location/scripts/install.sh

Basically if the key is empty don't attempt to write an empty string.
This only affects MySQL users who have `STRICT_TRANS_TABLES` enabled however as of version 5.7.5 this is the default value.

location - Fix mysql error with strict tables

---

app/modules/wifi/wifi_model.php

...when WiFi is off and table is empty. Bug found by eholtam

Fix for null integers

---

CHANGELOG.md
app/helpers/site_helper.php
app/views/listing/location.php
app/views/listing/munki.php
app/views/report/location.php
assets/locales/fr.json

Hi 
I've been testing the WIP branch as there are so very nice new shiny feature ( thanks all for them) 
But when i click on a client the page hangs trying to load, i have to stop to loading of the page to see the data
I suspect it is doing a look up on-line and as we dont have internet access it is failing 
Any suggestions
Thanks
Adam

Wip  Testing: Hangs on client page

---

assets/locales/de.json

Added the missing words, hope there are no typos anymore...:-)
Bye, Frido

Updated German translation for GSX, Location and WiFi modules

---

app/modules/wifi/scripts/wifi
app/modules/wifi/wifi_model.php
app/views/widgets/wifi_state_widget.php
assets/locales/en.json

Bug fix for WiFi part of issue #429, bugs found by @slackmac

Fixes for unknown and Internet Connection Sharing in WiFi module

---

app/modules/location/scripts/install.sh

Sorry evidently when I fixed #433 I made a copy/paste error.

Properly right location preference

---

app/modules/wifi/scripts/wifi
app/modules/wifi/wifi_model.php

Fixes WiFi module when WiFi is turned off

Fix for WiFi being turned off

---

app/lib/gsxlib/gsxlib.php

May 2016 GSX API changes will break MunkiReport's GSX integration unless updated gsxlib is used.

Update gsxlib for May 2016 GSX API changes

---

app/views/install/install_script.php

Fix preinstall and post install scripts so they're using $3 for the target volume

Fix target volume

---

build/addmodule.sh
build/scripts/install.sh
build/templates/controller.php
build/templates/install.sh
build/templates/model.php
build/templates/module_script.sh
build/templates/uninstall.sh

Running build/addmodule.sh module_name will generate a skeleton for a
new module

Add module templating

---

assets/locales/en.json

To match all the other dropdown menus

Clean Up Syntax

---

assets/locales/fr.json

Update fr - Captcha

---

app/modules/munkiinfo/scripts/munkiinfo.py

Resubmiting pull request #449 against `wip` branch as suggested by @clburlison

Capitalize Apple SoftwareUpdate identifier in munkiinfo.py script

---

app/views/listing/inventory.php

Added serial column and adjusted existing links to reference correct columns.
Addresses https://github.com/munkireport/munkireport-php/issues/537

Added Serial number column to fix client link

---

app/views/partials/head.php
assets/js/clients/client_list.js

Addressing https://github.com/munkireport/munkireport-php/issues/540

Added mananger role to show Edit button

---

app/modules/wifi/wifi_model.php

Remove double public in get_wifi_state()

---

app/modules/backup2go/backup2go_controller.php
app/modules/backup2go/backup2go_model.php
app/modules/backup2go/scripts/backup2go.sh
app/modules/backup2go/scripts/install.sh
app/modules/backup2go/scripts/uninstall.sh
app/modules/backup2go/views/backup2go_widget.php
app/views/listing/backup2go.php
app/views/report/backup.php
assets/locales/en.json

Archiware Backup2go initial push

Backup2go reporting

---

app/views/client/location_tab.php
app/views/listing/location.php
assets/locales/en.json

Listing and client tab had bad dates. Fixed with additional checking and moment.js

Location module dates fixes

---

app/views/listing/appusage.php
app/views/listing/backup2go.php
app/views/listing/certificate.php
app/views/listing/clients.php
app/views/listing/directoryservice.php
app/views/listing/disk.php
app/views/listing/displays.php
app/views/listing/gsx.php
app/views/listing/inventory.php
app/views/listing/munki.php
app/views/listing/network.php
app/views/listing/power.php
app/views/listing/profile.php
app/views/listing/sccm_status.php
app/views/listing/softwareupdate.php
app/views/listing/warranty.php
assets/locales/en.json

Localized and cleaned up all listings

Localize all listings

---

app/modules/usb/usb_model.php

Changed USB exclusion method

---

assets/locales/de.json

Added some terms for the new modules and changed "Bericht" to "-Report" (sounds less stilted)

Added and changed german localization

---

app/views/listing/appusage.php

Fixed the App Usage view to show Activation events from munki's app usage tracking.

Fix app usage view to show Activation Event

---

app/modules/power/power_model.php

Broke one of the battery widgets with the Power module rewrite.

Fixed battery widget

---

app/modules/timemachine/scripts/timemachine
app/modules/timemachine/timemachine_model.php

Fixed client script and added checks to model

Time Machine on Lion fix

---

app/modules/fan_temps/views/fan_temps_listing.php
app/modules/fan_temps/views/fan_temps_tab.php

Changed fans to fan_temps in views

Fixed fan_temps locales

---

app/modules/smart_stats/scripts/smart_stats.sh
app/modules/smart_stats/smart_stats_model.php

non-numeric in int values. Bugs found by @poundbangbash

Fixed handling of returns/newlines and

---

app/modules/gpu/gpu_model.php
app/modules/gpu/views/gpu_listing.php

and remove gmux version from listing

Set correct amount of VRAM for GMA950

---

app/modules/disk_report/views/disk_listing.php
app/modules/disk_report/views/disk_type_widget.php

Adjusted name for disk from Volume to Storage to better reflect the data type.

Localization fixes

---

app/modules/homebrew/locales/en.json

Fixed localization in the homebrew tab.

Fixed localization

---

app/modules/power/power_model.php

Fixed bug discovered by @gmarnin

Fixed power model

---

app/modules/displays_info/views/displays_tab.php
app/modules/munkireportinfo/munkireportinfo_model.php
app/modules/power/power_model.php
app/modules/servermetrics/servermetrics_model.php

Fixed MRinfo version corruption and servermetrics bug found by @gmarnin

Munkireportinfo and servermetrics model fixes

---

app/modules/printer/views/printers_listing.php

Fix for issue 687

---

app/modules/disk_report/views/disk_type_widget.php

Fix volume type widget

---

app/modules/power/power_controller.php
app/modules/power/power_model.php

Issue 697 fix

---

app/modules/managedinstalls/views/pending_widget.php

Adjusted the name of the fontawesome icon for the pending_widget to display properly.

Fixed fa icon

---

app/modules/bluetooth/bluetooth_model.php

Fix for Bluetooth false error

---

app/modules/power/power_model.php

Check for cell voltage

---

app/modules/smart_stats/locales/en.json
app/modules/smart_stats/views/smart_stats_listing.php

Add drive number to SMART Stats listing

---

app/modules/usb/usb_model.php

Added items that were showing up categorized as "Unknown" to capture them in the appropriate categories.

USB additions

---

app/modules/power/power_model.php

Changed how nulls are detected

Fixed power model formatting

---

app/modules/munkiinfo/locales/en.json
app/modules/munkiinfo/provides.php
app/modules/munkiinfo/views/munkiinfo_listing.php
app/modules/munkireport/views/munki_listing.php

Split munkiinfo listing from munkireport listing

Fix for empty munkiinfo db

---

app/modules/munkiinfo/views/munkiinfo_munkiprotocol_widget.php

To use the new munkiinfo listing

Updated Munki protocol widget

---

app/controllers/clients.php
app/modules/security/README.md
app/modules/security/locales/en.json
app/modules/security/migrations/005_security_add_firewall_state.php
app/modules/security/scripts/security.py
app/modules/security/security_controller.php
app/modules/security/security_model.php
app/modules/security/views/security_listing.php
app/views/client/summary_tab.php

FR from @mattiasvdm on macadmins slack. Simply shells out a defaults read and processes appropriately.

Add firewall state reporting

---

app/modules/user_sessions/README.md
app/modules/user_sessions/locales/en.json
app/modules/user_sessions/provides.php
app/modules/user_sessions/scripts/install.sh
app/modules/user_sessions/scripts/uninstall.sh
app/modules/user_sessions/scripts/user_sessions.py
app/modules/user_sessions/user_sessions_controller.php
app/modules/user_sessions/user_sessions_model.php
app/modules/user_sessions/views/user_sessions_listing.php
app/modules/user_sessions/views/user_sessions_tab.php

Jointly made by pudquick, clburlison, and tuxudo

User Sessions module

---

app/modules/security/provides.php
app/modules/security/security_model.php
app/modules/security/views/firewall_state_widget.php
app/modules/security/views/security.php

Adds a simple firewall state widget that counts the three possible states.

add firewall state widget

---

app/modules/certificate/views/certificate_tab.php

Tab view needed an adjustment for the 1 month "soon" value

Tab view change for 1 month "soon" value

---

app/modules/appusage/appusage_model.php

Bug discovered by @poundbangbash

Fixed app usage widget duplicates

---

app/modules/security/scripts/security.py

Improves error handling around the firmwarepasswd binary

add error handling around firmware pasword checks in 10.11.5 and up

---

app/modules/power/views/battery_tab.php
app/modules/smart_stats/locales/en.json
app/modules/smart_stats/views/smart_stats_tab.php

Move drive health in SMART Stats and cleaned up battery client tab

Client tabs cleanup

---

app/modules/extensions/README.md
app/modules/extensions/extensions_controller.php
app/modules/extensions/extensions_model.php
app/modules/extensions/locales/en.json
app/modules/extensions/provides.php
app/modules/extensions/scripts/extensions.py
app/modules/extensions/scripts/install.sh
app/modules/extensions/scripts/uninstall.sh
app/modules/extensions/views/extensions_listing.php
app/modules/extensions/views/extensions_tab.php
app/modules/extensions/views/extensions_widget.php

Module for reporting on third party extensions

Extensions Module

---

config_default.php

Added filters that are useful to reduce the noise in the inventory module.

Added more deafult filters for inventory module

---

app/views/install/install_script.php
config_default.php

Custom name of pre-/postflight and report_broken_client scripts

Custom script names

---

app/modules/extensions/extensions_controller.php
app/modules/extensions/extensions_model.php
app/modules/extensions/locales/en.json
app/modules/extensions/provides.php
app/modules/extensions/views/extensions_codesign_widget.php
app/modules/extensions/views/extensions_report.php

Added an Extensions report and widget that shows the codesign Team ID.

Add Extensions report and codesign widget.

---

app/modules/appusage/scripts/appusage
app/modules/caching/scripts/caching
app/modules/extensions/scripts/extensions.py
app/modules/fan_temps/scripts/fan_temps.sh
app/modules/sccm_status/scripts/sccm_status_info.sh
app/modules/service/scripts/service_check
app/modules/softwareupdate/scripts/softwareupdate.sh
app/modules/wifi/scripts/wifi

speeds up checking for updates in Managed Software Center

Added skips for manual checks

---

app/modules/certificate/scripts/cert_check

Certificate Module fix for multiple certs with same name

---

app/modules/machine/views/hardware_basemodel_widget.php

Embiggen the hardware base model widget

Embiggen hardware base model widget

---

app/modules/smart_stats/scripts/smart_stats.sh

Fixed APFS drives from showing up twice in SMART Stats

Fixes duplicate APFS drives in SMART Stats

---

app/modules/usage_stats/usage_stats_model.php

Bug found by @poundbangbash. Module was created for older version of MR before the models were redesigned.

Fixed Usage Stats Model

---

app/modules/applications/Illuminate Migration/2017_12_17_0000001_applications.php
app/modules/applications/README.md
app/modules/applications/applications_controller.php
app/modules/applications/applications_model.php
app/modules/applications/locales/en.json
app/modules/applications/provides.php
app/modules/applications/scripts/applications.py
app/modules/applications/scripts/install.sh
app/modules/applications/scripts/uninstall.sh
app/modules/applications/views/applications_listing.php
app/modules/applications/views/applications_tab.php

Module gets information on apps installed on a client. Also contains MR3 migration file

Applications Module

---

app/modules/smart_stats/locales/en.json

Fixed localization of SMART Stats module.

Issue #930 fix

---

app/modules/homebrew/migrations/2017_12_17_0000001_homebrew.php

Added missing column to homebrew module

Issue #928 Fix

---

app/modules/usage_stats/README.md
app/modules/usage_stats/locales/en.json
app/modules/usage_stats/migrations/2017_12_22_143049_usage_stats.php
app/modules/usage_stats/scripts/usage_stats
app/modules/usage_stats/usage_stats_model.php
app/modules/usage_stats/views/usage_stats_tab.php

Cleaned up usage stats cache file and improved error handling

Fix for Issue #927

---

app/modules/disk_report/disk_report_controller.php
app/modules/disk_report/disk_report_model.php
app/modules/disk_report/locales/en.json
app/modules/disk_report/provides.php
app/modules/disk_report/views/disk_type_widget.php
app/modules/disk_report/views/filesystem_type_widget.php
app/modules/disk_report/views/storage_report.php

Added filesystem widget

---

app/modules/certificate/certificate_model.php
app/modules/certificate/locales/en.json

Certificate localize fixes

---

app/modules/smart_stats/views/smart_overall_health_test_widget.php

Minor fix for missing widget title.

Smart stats widget title localization fix

---

app/modules/disk_report/disk_report_model.php

Fixes "Server Error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'internal' at row 1" error

Disk report error fix

---

app/modules/extensions/migrations/2018_02_12_164431_extensions_add_teamid.php

Fixed migration to have a unique file and class name.

Extensions migration name fix

---

app/modules/deploystudio/lib/deploystudio_helper.php

Was throwing an error and not processing correctly.

Fixed DeployStudio processing on MR3

---

app/modules/bluetooth/bluetooth_model.php
app/modules/bluetooth/locales/en.json
app/modules/bluetooth/scripts/bluetooth.py
public/assets/js/clients/client_detail.js

Current module fails on devices that don't have Bluetooth

Check for no Bluetooth in BT module

---

app/modules/security/scripts/security.py
app/modules/timemachine/scripts/timemachine

instead of "plutil -convert xml1"

Changed Time Machine and security modules to use FountationPlist

---

app/modules/filevault_escrow/README.md

Munkireport will fail to load if config.php has a syntax error

A ; is required to a have a valid config

---

app/modules/applications/applications_controller.php
app/modules/applications/applications_model.php
app/modules/applications/locales/en.json
app/modules/applications/provides.php
app/modules/applications/views/applications_32-bit_apps_widget.php

Added widget for 32-bit apps

---

app/helpers/gsx_helper.php
config_default.php

Added support for different ship to in GSX

---

app/modules/profile/locales/en.json
app/modules/profile/profile_controller.php
app/modules/profile/profile_model.php
app/modules/profile/provides.php
app/modules/profile/views/profile_group_widget.php
app/modules/profile/views/profile_report.php

Attempt at #860
This creates a Profiles report and widget that lists the unique profiles an a count for each. 
Clicking on the profile name in the widget links to a filtered search in the listing against the profile name.
-Eric

Profile count report

---

app/modules/security/scripts/security.py

Further to 13900e84, actually fix SIP reporting.

Actually fix security.py module

---

app/modules/filevault_escrow/README.md
app/modules/filevault_escrow/filevault_escrow_controller.php

Added a checkin url to spoof a crypt server. This will respond with a 200 to stop the crypt client from attempting to escrow every 2 minutes.

Added basic crypt checkin url

---

app/modules/reportdata/views/clients_listing.php

Requested in PR #1085 by @gmarnin

Added Registration Date to listing

---

app/modules/deploystudio/lib/deploystudio_helper.php

Bug found by steffan on MacAdmins Slack

Fix for no workflow title

---

app/modules/security/locales/en.json
app/modules/security/provides.php
app/modules/security/security_controller.php
app/modules/security/security_model.php
app/modules/security/views/security.php
app/modules/security/views/ssh_state_widget.php

Added SSH state stats widget to the Security report.

Added ssh status widget to report

---

app/modules/gpu/gpu_model.php
app/modules/gpu/scripts/gpu.py

Chagned metal columns to match database. Bug found by @poundbangbash

Fix for issue #1102

---

app/modules/security/scripts/security.py

ARD groups were showing duplicates.
Fixed the script to only add unique values.

Addressed duplication of ARD groups.

---

app/modules/detectx/README.md
app/modules/detectx/detectx_controller.php
app/modules/detectx/detectx_model.php
app/modules/detectx/locales/en.json
app/modules/detectx/migrations/2018_08_17_094300_detectx.php
app/modules/detectx/views/detectx_tab.php
app/modules/detectx/views/detectx_widget.php

Fixed some duplication issues
Fixed some spacing issues
Added some better status breakdown logic:
- Infection/Issue status can now be determined individually

Detectx patch

---

app/controllers/clients.php

Show machine group name instead of number

---

config_default.php

Added '32_bit_apps' to list of available widgets in config_default.php

Added '32_bit_apps' to list of available widgets

---

app/controllers/settings.php
app/views/partials/head.php
config_default.php
public/assets/js/munkireport.settings.js

Config option to set the default theme for new users/logins. May need to clear cache and local data if already logged in.

Add support for default theme

---

app/modules/profile/views/profile_listing.php

Added support for machine groups in profile listing

---

app/modules/munki_facts/munki_facts_model.php

Added machine group filtering to munki_facts widget

---

app/modules/certificate/certificate_model.php

Add machine group filtering to cert widget

---

app/modules/gpu/scripts/gpu.py

Bug reported by steffan on MacAdmins Slack

Fixed GPU for Macs without Metal support

---

app/modules/ibridge/README.md
app/modules/ibridge/ibridge_controller.php
app/modules/ibridge/ibridge_model.php
app/modules/ibridge/locales/en.json
app/modules/ibridge/migrations/2018_07_27_0000001_ibridge.php
app/modules/ibridge/provides.php
app/modules/ibridge/scripts/ibridge.py
app/modules/ibridge/scripts/install.sh
app/modules/ibridge/scripts/uninstall.sh
app/modules/ibridge/views/ibridge_listing.php
app/modules/ibridge/views/ibridge_tab.php
app/modules/ibridge/views/ibridge_widget.php

As requested by @gmarnin, who also helped with debugging :) Resolves issue #1113

Added iBridge module

---

config_default.php

Example updates and spacing cleanup (tabs vs. spaces) for consistency.

Updated config_default.php

---

build/templates/en.json
build/templates/provides.php

Looks to be leftover from when the template was created.

Removing unnecessary data

---

build/templates/install.sh

Putting this one against wip. Sorry about that!

Including preset curl options by default

---

app/helpers/site_helper.php
database/migrate.php

Fix migrate.php

---

app/views/partials/head.php
public/assets/js/munkireport.js

Resolves feature request #1147

Added F for machine filter popup

---

app/views/client/summary_tab.php
public/assets/locales/de.json
public/assets/locales/en.json
public/assets/locales/fr.json
public/assets/locales/nl.json
public/assets/locales/ru.json

To prevent conflicts with memory module's localization

Change 'memory' localization name

---

public/assets/js/munkireport.settings.js

(Should this be moved to the displays_info module?)

Added AirPlay to vendors

---

build/config/config_to_env.yml

Continuation of https://github.com/munkireport/munkireport-php/pull/1252

Remove duplicate hosts key

---

build/mr_upgrade.py

nailed it. first try!
sample output:
```
cwhits:/Volumes/Data/dev/munkireport-php $ ./build/mr_upgrade.py --upgrade --no-backup                                                                                                        
[2020-04-03 11:05:23] [INFO    ] Current version: 5.3.0.3990                                                                                                                                                
[2020-04-03 11:05:23] [INFO    ] Latest version:  5.3.5                                                                                                                                                     
[2020-04-03 11:05:23] [INFO    ] Install path:    /Volumes/Data/dev/munkireport-php/ …
```

Updating the mr upgrade script

---

build/mr_upgrade.py

Included a try/catch block around the imports to ensure that a user properly installs the requirements using the requirements.txt file. Additionally, includes various changes by @cwhits for a git fetch following the pull.

Import validation checks and modifying git fetch

---

app/lib/munkireport/Widgets.php
app/views/widgets/spacer_widget.php

Added spacer_widget.php
In dashboard yml file, specify spacer:
If larger than 2 columns spacer needed, use spacer: { size:3 }

Added spacer_widget with customizable size

---

app/config/app.php
app/controllers/Admin.php
app/controllers/Archiver.php
app/controllers/Manager.php
app/helpers/site_helper.php
app/lib/munkireport/AuthHandler.php
app/lib/munkireport/User.php
app/models/Business_unit.php
app/views/admin/business_units.php
app/views/client/client_detail.php
app/views/partials/head.php
docs/authorization.md
public/assets/js/clients/client_detail.js
system/kissmvc.php

This is a first attempt to create a new Role of "Archiver" that allows users in this role archive machines but not delete. Since Archiving is not a destructive change it makes sense to have this role be accessible to techs/staff that can archive machines that they know are going out of use but not lose the historical asset information that a delete would cause.
I'm not familiar with Machine Groups or how it integrates with different roles so a keen eye will need to be cast over this PR to make sure the necessary changes are made in that respect.
-Eric

Add archiver role

---

docker-compose.yml.example

Updated "ombrew" to "homebrew" in the module section of this example doc

Update Docker Module Name

---

app/config/app.php
app/lib/munkireport/Modules.php
local/modules/README.md

Adding a default search path for custom modules in the local directory.

Local module directory

---

app/controllers/Install.php
app/views/install/install_script.php

Add target locations fixes #1335

Update install scripts

---

public/assets/locales/en.json

This change accurately reflects what the Database link this for

Update Database Link Name

---

Dockerfile
php/upload.ini

Use a more secure php.ini and make some custom changes there.
fix for #1403

using php.ini-production and configure php upload settings

---

app/Http/Controllers/Api/SystemInformationController.php
app/Http/Controllers/ReportDataController.php
app/Http/Controllers/ShowController.php
app/Http/Controllers/SystemController.php
docs/illuminate/docker-v6.md
resources/views/errors/403.blade.php
resources/views/errors/404.blade.php
resources/views/errors/426.blade.php
resources/views/errors/503.blade.php
resources/views/system/status.blade.php
routes/api.php
tests/Feature/AdminControllerTest.php
tests/Feature/Api/SystemInformationControllerTest.php
tests/Feature/ArchiverControllerTest.php
tests/Feature/MachineControllerTest.php
tests/Feature/ReportDataControllerTest.php
tests/Feature/SettingsControllerTest.php
tests/Feature/ShowControllerTest.php
tests/Feature/UnitControllerTest.php

Add comments which explain actions that are only partially migrated.
Add v6 docker notes
Create error pages which have the same style as v5 error view
Increase test coverage, in some cases marking inadequate tests as incomplete.

General view clean up and testing improvement

---

.github/workflows/build-adhoc.yml
.github/workflows/release-tag.yml
.github/workflows/test.yml

Add an ad-hoc build and upload workflow, to test artifact release build process
Add a release-on-tag workflow which is incomplete.
Rename `build and test` to just `test`, because the workflow is really about testing, building is a side effect.

GitHub Actions Improvements

---

docker-compose.yml.example

fix the image in the docker-compose example
Part of #1465

Fix docker compose image

---

public/assets/client_installer/payload/usr/local/munkireport/munkireport-runner

Update munkireport-runner --remove-python2
